networks:
  voicecan-network:
    external: true

services:
  aiavatar-web:
    image: taito/aiavatar-web:latest
    container_name: aiavatar-web
    volumes:
      - ./shared_data/face2face:/usr/share/nginx/html/face2face
    # ports:
    #   - '80:80'
    networks:
      - voicecan-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.aiavatar-web.rule=Host(`avatar.yourdomain.com`)
      - traefik.http.routers.aiavatar-web.tls=true
      - traefik.http.routers.aiavatar-web.tls.certresolver=myresolver
      - traefik.http.routers.aiavatar-web.middlewares=redirect-to-https@file,cors@file