# build stage
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_DOMAIN_SUFFIX
ENV VITE_DOMAIN_SUFFIX=$VITE_DOMAIN_SUFFIX
RUN echo "VITE_DOMAIN_SUFFIX=$VITE_DOMAIN_SUFFIX" > .env.production
RUN npm run build

# production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
